services:
  mongodb:
    image: mongo:7.0
    container_name: recipe-app-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: recipe-app
    volumes:
      - mongodb_data:/data/db
      - ./mongodb-init:/docker-entrypoint-initdb.d
    networks:
      - recipe-app-network

  mongo-express:
    image: mongo-express:1.0.2
    container_name: recipe-app-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    networks:
      - recipe-app-network

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: recipe-app-server
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      MONGODB_URI: mongodb://recipeapp:recipeapp123@mongodb:27017/recipe-app?authSource=recipe-app
      JWT_SECRET: your_super_secret_jwt_key_for_production_change_this
      NODE_ENV: development
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - recipe-app-network

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: recipe-app-client
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      VITE_API_BASE_URL: http://localhost:3001/api
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    networks:
      - recipe-app-network

volumes:
  mongodb_data:
    driver: local

networks:
  recipe-app-network:
    driver: bridge